# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://developer.hashicorp.com/packer/tutorials/docker-get-started/get-started-install-cli
steps:
  - id: "Check Version"
    name: 'gcr.io/$PROJECT_ID/packer'
    args:
      - --version
      - |
        > /workspace/build_version.txt

  - id: "Read Output"
    name: 'gcr.io/$PROJECT_ID/packer'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        source /workspace/build_version.txt &&
        cat  /workspace/build_version.txt

