# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://developer.hashicorp.com/packer/tutorials/docker-get-started/get-started-install-cli
steps:
  - name: 'gcr.io/$PROJECT_ID/packer'
    args:
      - --version

artifacts:
  objects:
    location: 'gs://image_build_artifacts/'
    paths: ['cloudbuild.yaml','packimage_cloudbuild.yaml','packer.json']

